# Generated by Django 5.0.6 on 2024-06-20 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="contributor",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_time"]},
        ),
    ]
